
spring:
  # 配置数据源
  datasource:
    ## 配置数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    ## 数据源基本配置
    username: proxy
    password: 123456
    url: jdbc:mysql://192.168.0.109:4000/mbms?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## 配置SpringBoot上传文件的大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  ## 配置thymeleaf缓存
  thymeleaf:
    cache: false

## 配置 MyBatisy
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

## 配置素材上传路径
file:
  heads: images/upload/heads/
  material:
    picture: images/upload/materialbase/picture/
    video: images/upload/materialbase/video/

## 配置线程池属性
task:
  thread:
    pool:
      corePoolSize: 100
      maxPoolSize: 1000
      keepAliveSeconds: 60
      queueCapacity: 100
      threadNamePrefix: "uploadAsync-"

