
spring:
  # 配置数据源
  datasource:
    ## 配置数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    ## 数据源基本配置
    username: proxy
    password: 123456
    url: jdbc:mysql://192.168.0.109:4000/mbms?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

# 配置 MyBatisy
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# 配置 FTP
ftp:
  upload:
    host: 192.168.0.125
    port: 22
    username: root
    password: root123
    basePath: /opt/file-server/
    filePath: images/upload/heads/